import { getIndex } from "@/lib/wallpapers";
import { LandingClient } from "./LandingClient";
import { HeroVideo } from "@/app/components/landing/HeroSection";

export const dynamic = 'force-static'; // Ensure it's statically generated by Vercel for free tier performance
export const revalidate = 3600; // Revalidate every hour if we want to occasionally pick new random videos

export default function Page() {
    const idx = getIndex();
    let heroVideos: HeroVideo[] = [];

    if (idx) {
        // Pick a random subset of 15 wallpapers (mostly static images) to pass to the client 
        // During build time (SSG), this generates a fixed subset. 
        // Client will pick 1 out of these 15 randomly on each page load, then crossfade them.
        const allEntries = idx.entries;
        const shuffled = [...allEntries].sort(() => 0.5 - Math.random());
        const selected = shuffled.slice(0, 15);
        
        heroVideos = selected.map(e => {
            const url = e.url;
            const isVideo = url.endsWith(".mp4") || url.endsWith(".webm");
            return {
                src: url,
                type: isVideo ? (url.endsWith(".mp4") ? "video/mp4" : "video/webm") : "image/jpeg",
                // For videos, guess the poster. For images, the image itself is the poster!
                poster: isVideo ? url.replace(/\.(webm|mp4)$/, ".webp").replace("/videos/", "/videos/posters/") : url
            };
        });
    }

    return <LandingClient heroVideos={heroVideos.length > 0 ? heroVideos : undefined} />;
}
