import { NextResponse } from 'next/server';
import { getDb } from '@/lib/mongodb';

// in-memory hot cache for zero-latency public get responses
let inMemoryOiCache: any = null;
let lastCacheUpdateMs: number = 0;

// cors headers allowing universal access from any external frontend or script
const CORS_HEADERS = {
    'Access-Control-Allow-Origin': '*',
    'Access-Control-Allow-Methods': 'GET, POST, OPTIONS',
    'Access-Control-Allow-Headers': 'Content-Type, Authorization, x-sync-secret',
};

// options handler for cors preflight requests
export async function OPTIONS() {
    return new NextResponse(null, {
        status: 204,
        headers: CORS_HEADERS,
    });
}

// public get endpoint: callable by anyone without authentication
// returns the latest sovereign aggregated open interest snapshot
export async function GET() {
    try {
        // 1. check hot memory cache first if updated recently (< 30 seconds old)
        if (inMemoryOiCache && (Date.now() - lastCacheUpdateMs < 30_000)) {
            return NextResponse.json(
                { success: true, source: 'memory_cache', data: inMemoryOiCache },
                {
                    status: 200,
                    headers: {
                        ...CORS_HEADERS,
                        'Cache-Control': 'public, s-maxage=60, stale-while-revalidate=120',
                    },
                }
            );
        }

        // 2. retrieve latest snapshot from mongodb
        try {
            const db = await getDb();
            const collection = db.collection('market_metrics');
            const record = await collection.findOne({ metric: 'aggregated_open_interest' });

            if (record && record.data) {
                inMemoryOiCache = record.data;
                lastCacheUpdateMs = Date.now();
                return NextResponse.json(
                    { success: true, source: 'database', data: record.data, updated_at: record.updated_at },
                    {
                        status: 200,
                        headers: {
                            ...CORS_HEADERS,
                            'Cache-Control': 'public, s-maxage=60, stale-while-revalidate=120',
                        },
                    }
                );
            }
        } catch (dbErr) {
            console.warn('[open-interest-api] database lookup warning:', dbErr);
        }

        // 3. fallback to cached memory object if database was unavailable
        if (inMemoryOiCache) {
            return NextResponse.json(
                { success: true, source: 'memory_fallback', data: inMemoryOiCache },
                {
                    status: 200,
                    headers: CORS_HEADERS,
                }
            );
        }

        // 4. default response when no sync has been received yet
        return NextResponse.json(
            {
                success: false,
                status: 'awaiting_initial_sync',
                message: 'no open interest snapshot has been synchronized yet from the local quant engine.',
            },
            {
                status: 200,
                headers: CORS_HEADERS,
            }
        );
    } catch (e) {
        console.error('[open-interest-api] unexpected get error:', e);
        return NextResponse.json(
            { success: false, error: 'internal server error' },
            { status: 500, headers: CORS_HEADERS }
        );
    }
}

// secure post endpoint: requires authentication header
// accepts the latest summary.json generated by the local sovereign engine
export async function POST(req: Request) {
    try {
        // 1. authenticate caller via x-sync-secret or bearer token
        const authHeader = req.headers.get('authorization') || '';
        const bearerToken = authHeader.startsWith('Bearer ') ? authHeader.slice(7).trim() : '';
        const syncSecret = req.headers.get('x-sync-secret') || bearerToken;

        const expectedSecret = process.env.OI_SYNC_SECRET || process.env.ADMIN_PASSKEY;

        if (!expectedSecret || syncSecret !== expectedSecret) {
            return NextResponse.json(
                { success: false, error: 'unauthorized: invalid or missing sync secret' },
                { status: 401, headers: CORS_HEADERS }
            );
        }

        // 2. parse received open interest summary payload
        const payload = await req.json();
        if (!payload || typeof payload !== 'object') {
            return NextResponse.json(
                { success: false, error: 'invalid payload: expected json object' },
                { status: 400, headers: CORS_HEADERS }
            );
        }

        const now = new Date();

        // 3. update hot in-memory cache
        inMemoryOiCache = payload;
        lastCacheUpdateMs = now.getTime();

        // 4. persist snapshot into mongodb collection 'market_metrics'
        try {
            const db = await getDb();
            const collection = db.collection('market_metrics');
            await collection.updateOne(
                { metric: 'aggregated_open_interest' },
                {
                    $set: {
                        metric: 'aggregated_open_interest',
                        data: payload,
                        updated_at: now.toISOString(),
                        updated_at_epoch_ms: now.getTime(),
                    },
                },
                { upsert: true }
            );
        } catch (dbErr) {
            console.warn('[open-interest-api] database persistence warning (cached in memory):', dbErr);
        }

        return NextResponse.json(
            {
                success: true,
                message: 'open interest summary synchronized successfully',
                updated_at: now.toISOString(),
            },
            { status: 200, headers: CORS_HEADERS }
        );
    } catch (e) {
        console.error('[open-interest-api] post sync error:', e);
        return NextResponse.json(
            { success: false, error: 'failed to process sync payload' },
            { status: 500, headers: CORS_HEADERS }
        );
    }
}
